-- MySQL Script generated by MySQL Workbench
-- Fri May  5 20:22:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_citt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_citt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_citt` DEFAULT CHARACTER SET utf8 ;
USE `hospital_citt` ;

-- -----------------------------------------------------
-- Table `hospital_citt`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_citt`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `rut` INT NOT NULL,
  `dv` CHAR(1) NOT NULL,
  `telefono` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_citt`.`signos_vitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_citt`.`signos_vitales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_medicion` TIMESTAMP NOT NULL,
  `presion_arterial` FLOAT NOT NULL,
  `frecuencia_cardiaca` FLOAT NOT NULL,
  `oxigeno` FLOAT NOT NULL,
  `temperatura` FLOAT NOT NULL,
  `frecuencia_respiratoria` FLOAT NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Signos_vitales_Paciente_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Signos_vitales_Paciente`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_citt`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_citt`.`historico_dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_citt`.`historico_dispositivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_solicitado` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `numero_serie` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Historico_dispositivo_Paciente1_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_dispositivo_Paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_citt`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_citt`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_citt`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `nombre_apellido` VARCHAR(50) NOT NULL,
  `rol` VARCHAR(50) NOT NULL,
  `paciente_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_Paciente1_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_Paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_citt`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_citt`.`parametro_paciente_normal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_citt`.`parametro_paciente_normal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peso` INT NOT NULL,
  `edad` INT NOT NULL,
  `estatura` INT NOT NULL,
  `p_min_oxigeno` FLOAT NOT NULL,
  `p_max_oxigeno` FLOAT NOT NULL,
  `p_min_presion_arterial` FLOAT NOT NULL,
  `p_max_presion_arterial` FLOAT NOT NULL,
  `p_min_temperatura` FLOAT NOT NULL,
  `p_max_termperatura` FLOAT NOT NULL,
  `p_min_frec_respiratoria` FLOAT NOT NULL,
  `p_max_frec_respiratoria` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_citt`.`caracteristicas_dinamicas_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_citt`.`caracteristicas_dinamicas_paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peso` FLOAT NOT NULL,
  `estatura` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_caracteristicas_dinamicas_paciente_Paciente1_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_caracteristicas_dinamicas_paciente_Paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_citt`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
